### ISSUE TITLE
在没有搜索建议时，搜索输入的词语

### ISSUE THREAD

**Issue by mpco** [zqzten/alfred-web-search-suggest#15]
目前，在没有搜索建议时，会退回到 Alfred 的默认搜索。
这种情况下，希望能够回车搜索输入的词语。

**Comment by zqzten** [comment]
这个可以通过自行配置 Web Search 做到，将 keyword 设为和触发相应 workflow 一样的即可，参见：https://github.com/zqzten/alfred-web-search-suggest#direct-search
