### ISSUE TITLE
[enhancement required] remain functionality when no searching candidate

### ISSUE THREAD

**Issue by hackroid** [zqzten/alfred-web-search-suggest#22]
![pic](https://i.loli.net/2020/11/16/6UTXZz7Hd8wlfaS.png)

Like the picture shows above, it seems that the search result went wrong functionally when there is no searching candidate (maybe a null list returned, sorry I'm not familiar with PHP and I haven't read your code yet).

Is there a way to keep the functionality? such as `Still search Bilibili for {query}...`, or the way shown below

![pic2](https://i.loli.net/2020/11/16/UlvB7DMctLPKh9O.png)

**Comment by zqzten** [comment]
You can add customized [direct search](https://github.com/zqzten/alfred-web-search-suggest#direct-search).
