### ISSUE TITLE
where should I set the proxy?

### ISSUE THREAD

**Issue by TheAlienMann** [zqzten/alfred-web-search-suggest#23]
where should I set the proxy? it seems like I can’t make it working like the screenshots.
could you pleas be more specific about setting it up?

thank you!

**Comment by zqzten** [comment]
As described in [proxy setting](https://github.com/zqzten/alfred-web-search-suggest#proxy-setting), can set proxy via [Alfred workflow environment variable](https://www.alfredapp.com/help/workflows/advanced/variables/#environment).

Here's a sample screenshot for that
![image](https://user-images.githubusercontent.com/22231232/101883323-0bad2680-3bd2-11eb-8d06-a2efda48a6d8.png)
