### ISSUE TITLE
维基百科、微博和Bangumi的搜索建议无法使用

### ISSUE THREAD

**Issue by jiaming-shi** [zqzten/alfred-web-search-suggest#25]
截至今天（2021年 2月24日）我测试的时候发现维基百科、微博和Bangumi的搜索建议无法显示出来。其他的是正常的。

**Comment by zqzten** [comment]
维基百科需要代理的，看下[代理配置](https://www.alfredapp.com/help/features/web-search/)是否正确吧；Bangumi 的接口比较慢（包含预览图），有时需要多等几秒；微博似乎确实是换接口了，回头我看一下。

**Comment by jiaming-shi** [comment]
维基百科可能是测试的时候晚上代理速度太慢，现在测试是正常的。
不过Bangumi就有点奇怪，直接在Chrome访问PHP文件中网址是没有问题的，但是在Alfred中等了几分钟也没有反馈。

**Comment by zqzten** [comment]
你在 Chrome 上访问 Bangumi 的时候走代理了吗？目前这个 workflow 里 Bangumi 没有走代理，不清楚是否有部分运营商屏蔽了 Bangumi

**Comment by zqzten** [comment]
另外，看了下微博目前的搜索建议强制要求登录了，后续将不再支持微博搜索建议。

**Comment by jiaming-shi** [comment]
> 你在 Chrome 上访问 Bangumi 的时候走代理了吗？目前这个 workflow 里 Bangumi 没有走代理，不清楚是否有部分运营商屏蔽了 Bangumi

没有走代理，Chrome中大概是3秒左右加载完毕搜索结果。

**Comment by zqzten** [comment]
目前我本地还是没能很好地复现 Bangumi 的问题，先关闭此 issue 了。
