### ISSUE TITLE
Unable to run task!

### ISSUE THREAD

**Issue by nickokgo** [zqzten/alfred-web-search-suggest#26]
I'm getting the following error when attempting to run. Any idea on how to fix?

**Unable to run task!**
Reason: launch path not accessible

It's likely that the folder required to run this task has somehow been deleted, perhaps syncing?

This error isn't that serious, just try again :)

Related Workflow Info...
Name: 'Web Search Suggest'
Folder:/Users/nick/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.935962E0-1F83-4535-A2FD-76DF6D177502

**Comment by zqzten** [comment]
Yeah it's probably related to some sync problem. This path is the installation dir of the workflow, so reinstall the workflow can solve this problem.
