### ISSUE TITLE
bilibili结果中关键词带<b></b>

### ISSUE THREAD

**Issue by SpecN997** [zqzten/alfred-web-search-suggest#27]
![Screen Shot 2021-09-15 at 6 23 32 PM](https://user-images.githubusercontent.com/13669961/133420002-6ff2f523-1afe-4481-b3e9-e1620fdf61a0.png)
请问是alfred哪里设置不对本来应该显示粗体却没有吗？
alfred 4.5.1 / catalina 10.15.7

**Comment by zqzten** [comment]
应该是 B 站 API 返回的问题，我适配下

**Comment by SpecN997** [comment]
> 
> 
> 应该是 B 站 API 返回的问题，我适配下

谢谢~
