### ISSUE TITLE
BUG 

### ISSUE THREAD

**Issue by RomanticHW** [zqzten/alfred-web-search-suggest#31]
For all searches, text beyond a certain length is invalidated

**Comment by RomanticHW** [comment]
如果我想搜索一段长文本通过baidu，它超过一定长度就会变成Google wiki or ama 搜索。
能否取消长度限制以及只限定一开始选定的搜索引擎

**Comment by zqzten** [comment]
我这里好像不能复现，再长的文本也会有一个默认的使用 XX 搜索的结果，可以发下你的搜索文本看看

**Comment by RomanticHW** [comment]
> 我这里好像不能复现，再长的文本也会有一个默认的使用 XX 搜索的结果，可以发下你的搜索文本看看

骚瑞，可能是我表述不清楚。
就比如说我想谷歌“为什么今天的月亮这么圆”，它就会调取搜索选项。然而我想要的是智能搜索“为什么今天的月亮这么圆”的结果，如果没有合适的搜索结果我再去选择默认搜索。
我不太熟悉workflowrer的流程，一顿操作也没找到query的长度限制。
想更改这个长度，能确保类似“为什么今天的月亮这么圆”这种长句也能被正确返回智能搜索结果

**Comment by zqzten** [comment]
query 是没有长度限制的，只取决于搜索引擎是否能返回建议。比如“为什么今天的月亮这么圆”在百度是可以返回建议的，谷歌就不行。

**Comment by RomanticHW** [comment]
十分感谢
