### ISSUE TITLE
google suggest无法使用

### ISSUE THREAD

**Issue by wYuanHpp** [zqzten/alfred-web-search-suggest#32]
按照要求配置了对于的proxy,  我使用的事clashx, 配的地址的 http://127.0.0.1:7890 , 这个地址我的iterm2是可以正常工作的, 有没有什么办法?

**Comment by wYuanHpp** [comment]
解决了, 需要把源码里的url地址替换成'https://suggestqueries.google.com/complete/search?output=toolbar&q=' 即可

**Comment by zqzten** [comment]
感谢反馈。应该是 Google 更新了搜索建议的 API，我近期会更新下这个模块。
