### ISSUE TITLE
wiki无法显示subtitle，wolfram无法使用

### ISSUE THREAD

**Issue by aiPenguin** [zqzten/alfred-web-search-suggest#33]
你好，

遇到了两个问题

1. 使用wiki搜索的时候不能正常显示词条描述，
<img width="726" alt="CleanShot 2022-02-19 at 11 46 09@2x" src="https://user-images.githubusercontent.com/46262493/154797906-e019dcb3-f5f1-4fad-932c-4f385e5ac3dc.png">

2. 无法使用wolfram搜索
<img width="727" alt="CleanShot 2022-02-19 at 11 46 57@2x" src="https://user-images.githubusercontent.com/46262493/154797925-fa2578c1-bc4f-4c81-8eb5-981ea26f300b.png">

这应该怎么处理啊？

**Comment by KanswerG** [comment]
同问，并且wiki在我这也无法正常使用
<img width="564" alt="截屏2022-02-26 下午6 28 44" src="https://user-images.githubusercontent.com/76435190/155839798-86df5bf4-bf3d-44a1-a534-494000079f52.png">
debug显示获取结果数量的count变量为null，不太懂php，也没去调试
<img width="1071" alt="截屏2022-02-26 下午6 30 39" src="https://user-images.githubusercontent.com/76435190/155839987-5b06f6a6-60e7-46bd-845b-70a11cf9badb.png">

**Comment by zqzten** [comment]
我看了一下，wiki 官方的接口确实不返回描述了，目前是只有标题，当然 shift 快速预览还是支持的；wolfram 接口有变化，我适配一下
