### ISSUE TITLE
wiki等无法正常使用

### ISSUE THREAD

**Issue by KanswerG** [zqzten/alfred-web-search-suggest#34]
同问，并且wiki在我这也无法正常使用
<img width="564" alt="截屏2022-02-26 下午6 28 44" src="https://user-images.githubusercontent.com/76435190/155839798-86df5bf4-bf3d-44a1-a534-494000079f52.png">
debug显示获取结果数量的count变量为null，不太懂php，也没去调试
<img width="1071" alt="截屏2022-02-26 下午6 30 39" src="https://user-images.githubusercontent.com/76435190/155839987-5b06f6a6-60e7-46bd-845b-70a11cf9badb.png">

_Originally posted by @KanswerG in https://github.com/zqzten/alfred-web-search-suggest/issues/33#issuecomment-1051977479_

**Comment by zqzten** [comment]
我这里实测没问题，可以检查下是否代理相关配置有问题导致请求没有正确拿到结果。如果无法定位问题的话可以试试在对应 php 脚本的第 17 行后面加上 `echo($response);`，就可以在 debug 日志里看到具体请求结果了。
