### ISSUE TITLE
WiKi 返回值总是 []

### ISSUE THREAD

**Issue by romantech** [zqzten/alfred-web-search-suggest#35]
目前没配置Proxy。
谷歌、亚马逊等其它的搜索结果显示都正常
只有WiKi搜索返回值总是`[]` (请见下图`{"items":[]}`)
<img width="828" alt="20220819_125439@2x" src="https://user-images.githubusercontent.com/8604840/185539527-66f20443-3c2f-48a8-ac34-5c7aebdfae5a.png">

**Comment by zqzten** [comment]
你的完整输入是什么，指定的是什么语言？

**Comment by romantech** [comment]
这是谷歌搜索正常显示的截图
- Alfred Workflow Keyword : `g`
- 输入内容 : `g java`

<img width="837" alt="20220820_123316@2x" src="https://user-images.githubusercontent.com/8604840/185727413-f702d0b7-c3cb-4c03-9750-2776ccca814a.png">
<img width="718" alt="20220820_123346@2x" src="https://user-images.githubusercontent.com/8604840/185727416-92ecda4a-8b87-49a2-936d-192fac77bc70.png">

---

这是WiKi不正常显示的截图。输入`wk java`之后应该显示[java](https://en.wikipedia.org/wiki/java)的搜索结果。
- Alfred Workflow Keyword : `wk`
- 输入内容 : `wk java`

<img width="835" alt="20220820_123548@2x" src="https://user-images.githubusercontent.com/8604840/185727479-001b75c2-07bd-433e-b363-37a790e6b64e.png">

<img width="718" alt="20220820_123741@2x" src="https://user-images.githubusercontent.com/8604840/185727529-a36a3b32-b37c-4aaf-ae92-97d4dc0feca5.png">


> 你的完整输入是什么，指定的是什么语言？

这是谷歌搜索正常显示的截图
- Alfred Workflow Keyword : `g`
- 输入内容 : `g java`

<img width="837" alt="20220820_123316@2x" src="https://user-images.githubusercontent.com/8604840/185727413-f702d0b7-c3cb-4c03-9750-2776ccca814a.png">
<img width="718" alt="20220820_123346@2x" src="https://user-images.githubusercontent.com/8604840/185727416-92ecda4a-8b87-49a2-936d-192fac77bc70.png">

---

这是WiKi不正常显示的截图。输入`wk java`之后应该显示[java](https://en.wikipedia.org/wiki/java)的搜索结果。
- Alfred Workflow Keyword : `wk`
- 输入内容 : `wk java`

<img width="835" alt="20220820_123548@2x" src="https://user-images.githubusercontent.com/8604840/185727479-001b75c2-07bd-433e-b363-37a790e6b64e.png">

<img width="718" alt="20220820_123741@2x" src="https://user-images.githubusercontent.com/8604840/185727529-a36a3b32-b37c-4aaf-ae92-97d4dc0feca5.png">

**Comment by romantech** [comment]
@zqzten 这是谷歌搜索正常显示的截图
- Alfred Workflow Keyword : `g`
- 输入内容 : `g java`

<img width="837" alt="20220820_123316@2x" src="https://user-images.githubusercontent.com/8604840/185727413-f702d0b7-c3cb-4c03-9750-2776ccca814a.png">
<img width="718" alt="20220820_123346@2x" src="https://user-images.githubusercontent.com/8604840/185727416-92ecda4a-8b87-49a2-936d-192fac77bc70.png">

---

这是WiKi不正常显示的截图。输入`wk java`之后应该显示[java](https://en.wikipedia.org/wiki/java)的搜索结果。
- Alfred Workflow Keyword : `wk`
- 输入内容 : `wk java`

<img width="835" alt="20220820_123548@2x" src="https://user-images.githubusercontent.com/8604840/185727479-001b75c2-07bd-433e-b363-37a790e6b64e.png">

<img width="718" alt="20220820_123741@2x" src="https://user-images.githubusercontent.com/8604840/185727529-a36a3b32-b37c-4aaf-ae92-97d4dc0feca5.png">

**Comment by zqzten** [comment]
wiki 是需要指定语言的，看一下[这里](https://github.com/zqzten/alfred-web-search-suggest#wikipedia)的说明的示例

**Comment by romantech** [comment]
@zqzten 啊。。原来这样，刚才试了一下运行正常。抱歉打扰您了！谢谢⚡️

**Comment by zqzten** [comment]
嗯，后续可以考虑增加这个功能
